# Generated by Django 5.2.5 on 2025-08-31 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0003_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
