# Generated by Django 5.2.5 on 2025-08-31 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0005_product_price_alter_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='salary')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='phone')),
            ],
        ),
    ]
