# Generated by Django 5.2.5 on 2025-09-02 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0007_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartStatus',
            fields=[
                ('status', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Cart Status')),
            ],
        ),
    ]
