# Generated by Django 5.2.5 on 2025-09-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0008_cartstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='id',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
