# Generated by Django 5.2.5 on 2025-09-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0009_alter_worker_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Cart ID'),
        ),
        migrations.AlterField(
            model_name='cartstatus',
            name='status',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Cart Status'),
        ),
    ]
