# Generated by Django 5.2.5 on 2025-09-03 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0012_alter_worker_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartStatus',
        ),
    ]
