# Generated by Django 5.2.5 on 2025-09-03 15:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0013_delete_cartstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeCart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_sent', models.PositiveIntegerField(default=0)),
                ('price_sent', models.BigIntegerField(default=0)),
                ('amount_received', models.PositiveIntegerField(default=0)),
                ('revenue', models.BigIntegerField(default=0)),
                ('revenue_total', models.BigIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='inventory_management.product')),
            ],
        ),
    ]
