# Generated by Django 5.2.5 on 2025-09-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0014_chargecart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chargecart',
            name='price_sent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='chargecart',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='chargecart',
            name='revenue_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
