# Generated by Django 5.2.5 on 2025-09-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0015_product_amount_alter_chargecart_price_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargecart',
            name='money_returned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='chargecart',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('finalizado', 'Finalizado')], default='pendiente', max_length=20),
        ),
    ]
