# Generated by Django 5.2.5 on 2025-09-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0016_chargecart_money_returned_chargecart_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargecart',
            name='amount_received',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='chargecart',
            name='amount_sent',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='chargecart',
            name='money_returned',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='chargecart',
            name='price_sent',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='chargecart',
            name='revenue',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='chargecart',
            name='revenue_total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
