# Generated by Django 5.2.5 on 2025-09-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0017_alter_chargecart_amount_received_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargecart',
            name='money_returned',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='chargecart',
            name='price_sent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='chargecart',
            name='revenue',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='chargecart',
            name='revenue_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
