# Generated by Django 5.2.5 on 2025-09-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0018_alter_chargecart_money_returned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargecart',
            name='amount_received',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='chargecart',
            name='amount_sent',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
