# Generated by Django 5.2.5 on 2025-09-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0019_alter_chargecart_amount_received_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargecart',
            name='amount_received',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chargecart',
            name='revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
