# Generated by Django 5.2.5 on 2025-09-04 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0021_cart_is_deleted_chargecart_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='chargecart',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='worker',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
