# Generated by Django 5.2.5 on 2025-09-04 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0023_cart_deleted_cart_deleted_by_cascade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='chargecart',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='is_deleted',
        ),
    ]
