# Generated by Django 5.1.4 on 2025-09-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0024_remove_cart_is_deleted_remove_chargecart_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargecart',
            name='money_returned',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='chargecart',
            name='revenue',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='chargecart',
            name='revenue_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True),
        ),
    ]
