# Generated by Django 5.1.4 on 2025-09-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0026_dailypartcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailypartcart',
            name='money_return_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dailypartcart',
            name='net_profit',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dailypartcart',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
