# Generated by Django 5.1.4 on 2025-09-06 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0027_alter_dailypartcart_money_return_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargecart',
            name='daily_part_cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charge_carts', to='inventory_management.dailypartcart'),
        ),
    ]
