# Generated by Django 5.1.4 on 2025-09-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0028_chargecart_daily_part_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailypartcart',
            name='status',
            field=models.CharField(choices=[('trabajando', 'Trabajando'), ('finalizado', 'Finalizado')], default='trabajando', max_length=20, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='worker',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('trabajando', 'Trabajando')], default='pendiente', max_length=20, verbose_name='status'),
        ),
    ]
