# Generated by Django 5.1.4 on 2025-09-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0029_dailypartcart_status_worker_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('trabajando', 'Trabajando')], default='pendiente', max_length=20, verbose_name='status'),
        ),
    ]
