# Generated by Django 5.1.4 on 2025-09-07 15:03

import django.db.models.deletion
import inventory_management.modules.product.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0030_cart_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Almacén Principal', max_length=100)),
                ('own_money', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('money_business', models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True)),
                ('percent', models.DecimalField(blank=True, decimal_places=2, default=30, max_digits=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(default=inventory_management.modules.product.models.get_default_store, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inventory_management.store'),
        ),
    ]
