# Generated by Django 5.1.4 on 2025-09-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0031_store_product_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='money_business',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='own_money',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
