# Generated by Django 5.1.4 on 2025-09-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0032_alter_store_money_business_alter_store_own_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('trabajando', 'Trabajando')], default='pendiente', editable=False, max_length=20, verbose_name='status'),
        ),
    ]
