# Generated by Django 5.1.4 on 2025-09-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0033_alter_worker_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargecart',
            name='amount_received',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='chargecart',
            name='amount_sent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
