# Generated by Django 5.1.4 on 2025-09-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0035_alter_product_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductCategory',
        ),
        migrations.AlterField(
            model_name='chargecart',
            name='amount_received',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
