# Generated by Django 5.1.4 on 2025-09-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0037_alter_chargecart_amount_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargecart',
            name='revenue_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
