# Generated by Django 5.1.4 on 2025-09-08 18:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0038_alter_chargecart_revenue_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargecart',
            name='amount_received',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
