# Generated by Django 5.1.4 on 2025-09-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0040_alter_chargecart_amount_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('trabajando', 'Trabajando')], default='pendiente', editable=False, max_length=20, verbose_name='status'),
        ),
    ]
