# Generated by Django 5.2.5 on 2025-09-10 23:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0041_alter_cart_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPart',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True, unique=True)),
                ('money_return_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('status', models.CharField(choices=[('trabajando', 'Trabajando'), ('finalizado', 'Finalizado')], default='trabajando', max_length=20, verbose_name='status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='dailypartcart',
            name='daily_part',
            field=models.ForeignKey(default='550e8400-e29b-41d4-a716-446655440000', on_delete=django.db.models.deletion.CASCADE, related_name='daily_part_carts', to='inventory_management.dailypart'),
            preserve_default=False,
        ),
    ]
