# Generated by Django 5.1.4 on 2025-09-12 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0042_dailypart_dailypartcart_daily_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailypart',
            name='store',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_parts', to='inventory_management.store'),
        ),
    ]
