# Generated by Django 5.1.4 on 2025-09-12 12:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0043_dailypart_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargecart',
            name='money_invested',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10),
        ),
    ]
