# Generated by Django 5.2.5 on 2025-09-13 01:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0043_wastagerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastagerecord',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
