# Generated by Django 5.1.4 on 2025-09-12 14:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0044_chargecart_money_invested'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailypart',
            name='money_invested',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailypartcart',
            name='money_invested',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10),
        ),
    ]
