# Generated by Django 5.2.5 on 2025-09-17 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0044_alter_wastagerecord_quantity'),
        ('inventory_management', '0045_dailypart_money_invested_and_more'),
    ]

    operations = [
    ]
