# Generated by Django 5.2.5 on 2025-09-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartStatus',
            fields=[
                ('status', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Cart Status')),
            ],
        ),
    ]
